name: compile pdf
on: [push]
jobs:
  Compile-PDF:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: AnalisiUno.tex
      - name: create PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: AnalisiUno.pdf
          path: AnalisiUno.pdf
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  Create-Release:
    runs-on: ubuntu-latest
    needs: Compile-PDF
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: create Release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "AnalisiUno.pdf"
          artifactContentType: "application/pdf"
          body: "new release!"
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "this job's status is ${{ job.status }}."